# Generated by Django 5.0.6 on 2024-07-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('sku', models.CharField(default='N/A', max_length=255)),
                ('price_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_sold', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('size', models.CharField(blank=True, default='N/A', max_length=10, null=True)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Lightly Used', 'Lightly Used')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Sneakers', 'Sneakers'), ('Streetwear', 'Streetwear')], default='Sneakers', max_length=50)),
                ('imageUrl', models.URLField(blank=True, default='https://example.com/default_image.jpg', null=True)),
                ('apparel_size', models.CharField(default='N/A', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Inventory',
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
