# Generated by Django 5.0.6 on 2024-07-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_inventory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(blank=True, choices=[('Sneakers', 'Sneakers'), ('Streetwear', 'Streetwear')], default='Sneakers', max_length=50),
        ),
    ]
