# Generated by Django 5.0.6 on 2024-07-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_inventory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='apparel_size',
            field=models.CharField(blank=True, default='N/A', max_length=255),
        ),
    ]
