# Generated by Django 5.0.6 on 2024-07-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_inventory_apparel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('Sold', 'Sold'), ('Available', 'Available')], default='Available', max_length=50),
        ),
    ]
