# Generated by Django 5.0.6 on 2024-08-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_profile_address_profile_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/default_image.jpg', null=True, upload_to='images/'),
        ),
    ]
