# Generated by Django 5.0.6 on 2024-08-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inventory_link',
            field=models.URLField(blank=True),
        ),
    ]
