# Generated by Django 5.0.6 on 2024-08-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_profile_inventory_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inventory_goal',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='profit_goal',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='sales_goal',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
