# Generated by Django 5.0.6 on 2024-08-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_profile_inventory_goal_profile_profit_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='inventory_goal',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sales_goal',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
