# Generated by Django 5.0.6 on 2024-08-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_profile_inventory_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/default_image.jpg', null=True, upload_to='profile_pic/'),
        ),
    ]
