# Generated by Django 5.0.6 on 2024-08-07 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='inventory_goal',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profit_goal',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sales_goal',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
