# Generated by Django 5.0.6 on 2024-08-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_inventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sold_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
