# Generated by Django 5.0.6 on 2024-08-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_inventory_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='price_paid',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
