# Generated by Django 5.0.6 on 2024-08-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_inventory_price_paid_alter_inventory_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
