# Generated by Django 5.0.6 on 2024-08-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_profile_total_inventory_profile_total_profit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='inventory_count',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='sold_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_inventory',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_profit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_sales',
        ),
        migrations.AddField(
            model_name='profile',
            name='inventory_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='profit_count',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sold_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
