# Generated by Django 5.0.6 on 2024-08-11 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_inventory_sold_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='sold_quantity',
        ),
    ]
