# Generated by Django 5.0.6 on 2024-08-12 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_inventory_sold_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('inventory_count', models.IntegerField(default=0)),
                ('sold_count', models.IntegerField(default=0)),
                ('profit_count', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('inventory_count', models.IntegerField(default=0)),
                ('sold_count', models.IntegerField(default=0)),
                ('profit_count', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='YearlyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('inventory_count', models.IntegerField(default=0)),
                ('sold_count', models.IntegerField(default=0)),
                ('profit_count', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'year')},
            },
        ),
    ]
