# Generated by Django 5.0.6 on 2024-08-14 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_dailymetrics_monthlymetrics_yearlymetrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='inventory_goal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profit_goal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sales_goal',
        ),
    ]
