# Generated by Django 5.0.6 on 2024-08-14 02:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_remove_profile_inventory_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymetrics',
            name='daily_inventory_goal',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='dailymetrics',
            name='daily_profit_goal',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='dailymetrics',
            name='daily_sales_goal',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='monthlymetrics',
            name='monthly_inventory_goal',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='monthlymetrics',
            name='monthly_profit_goal',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='monthlymetrics',
            name='monthly_sales_goal',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='yearlymetrics',
            name='yearly_inventory_goal',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='yearlymetrics',
            name='yearly_profit_goal',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='yearlymetrics',
            name='yearly_sales_goal',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
