# Generated by Django 5.0.6 on 2024-08-14 03:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_dailymetrics_daily_inventory_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymetrics',
            name='daily_inventory_goal',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='dailymetrics',
            name='daily_profit_goal',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dailymetrics',
            name='daily_sales_goal',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='monthlymetrics',
            name='monthly_inventory_goal',
            field=models.PositiveIntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name='monthlymetrics',
            name='monthly_profit_goal',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monthlymetrics',
            name='monthly_sales_goal',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='yearlymetrics',
            name='yearly_inventory_goal',
            field=models.PositiveIntegerField(default=18000),
        ),
        migrations.AlterField(
            model_name='yearlymetrics',
            name='yearly_profit_goal',
            field=models.DecimalField(decimal_places=2, default=36000, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='yearlymetrics',
            name='yearly_sales_goal',
            field=models.PositiveIntegerField(default=3600),
        ),
    ]
