# Generated by Django 5.0.6 on 2024-08-14 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_inventory_options_inventory_is_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='sold',
        ),
    ]
