# Generated by Django 5.0.6 on 2024-08-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_inventory_options_profile_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_logo',
            field=models.ImageField(default='company_pic/logo.jpg', upload_to=''),
        ),
    ]
