# Generated by Django 5.0.6 on 2024-08-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_profile_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(default='company_pic/logo.png', upload_to='')),
            ],
        ),
    ]
