# Generated by Django 5.1 on 2024-08-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_image_delete_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_goals',
            field=models.ImageField(blank=True, default='images/goals.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_inventorys',
            field=models.ImageField(blank=True, default='images/inventory.png', null=True, upload_to=''),
        ),
    ]
